// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using personelTrackingSystem.Persistence.Contexts;

#nullable disable

namespace personelTrackingSystem.Persistence.Migrations
{
    [DbContext(typeof(personelTrackingSystemDbContext))]
    [Migration("20240120174744_personelTrackingSystemUpdate")]
    partial class personelTrackingSystemUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("personelTrackingSystem.Domain.Entities.AnnualLeaveEntity", b =>
                {
                    b.Property<int>("LeaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveId"), 1L, 1);

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LeaveApplicationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LeaveEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LeaveStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.HasKey("LeaveId");

                    b.HasIndex("PersonelId");

                    b.ToTable("AnnualLeaveEntity");
                });

            modelBuilder.Entity("personelTrackingSystem.Domain.Entities.DepartmentEntity", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"), 1L, 1);

                    b.Property<string>("DepartmentHead")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("personelTrackingSystem.Domain.Entities.EntryEntity", b =>
                {
                    b.Property<int>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntryId"), 1L, 1);

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExitDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntryId");

                    b.HasIndex("PersonelId");

                    b.ToTable("EntryEntity");
                });

            modelBuilder.Entity("personelTrackingSystem.Domain.Entities.LateArrivalEntity", b =>
                {
                    b.Property<int>("ArrivalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArrivalId"), 1L, 1);

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LateArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LateArrivalTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonelID")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArrivalId");

                    b.HasIndex("PersonelID");

                    b.ToTable("LateArrivalEntity");
                });

            modelBuilder.Entity("personelTrackingSystem.Domain.Entities.PersonelEntity", b =>
                {
                    b.Property<int>("PersonelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonelId"), 1L, 1);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("NameSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("PersonelId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("TeamId");

                    b.ToTable("Personels");
                });

            modelBuilder.Entity("personelTrackingSystem.Domain.Entities.ProjectEntity", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"), 1L, 1);

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProjectEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProjectStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectId");

                    b.HasIndex("PersonelId");

                    b.ToTable("ProjectEntity");
                });

            modelBuilder.Entity("personelTrackingSystem.Domain.Entities.SalaryEntity", b =>
                {
                    b.Property<int>("SalaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalaryId"), 1L, 1);

                    b.Property<int>("IncreaseRate")
                        .HasColumnType("int");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<decimal>("PersonelSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SalaryDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SalaryId");

                    b.HasIndex("PersonelId");

                    b.ToTable("SalaryEntity");
                });

            modelBuilder.Entity("personelTrackingSystem.Domain.Entities.TeamEntity", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"), 1L, 1);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriorityLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TeamBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamId");

                    b.ToTable("TeamEntity");
                });

            modelBuilder.Entity("personelTrackingSystem.Domain.Entities.AnnualLeaveEntity", b =>
                {
                    b.HasOne("personelTrackingSystem.Domain.Entities.PersonelEntity", "Personel")
                        .WithMany("AnnualLeave")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("personelTrackingSystem.Domain.Entities.EntryEntity", b =>
                {
                    b.HasOne("personelTrackingSystem.Domain.Entities.PersonelEntity", "Personel")
                        .WithMany("EntryEntities")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("personelTrackingSystem.Domain.Entities.LateArrivalEntity", b =>
                {
                    b.HasOne("personelTrackingSystem.Domain.Entities.PersonelEntity", "Personel")
                        .WithMany("LateArrival")
                        .HasForeignKey("PersonelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("personelTrackingSystem.Domain.Entities.PersonelEntity", b =>
                {
                    b.HasOne("personelTrackingSystem.Domain.Entities.DepartmentEntity", "Department")
                        .WithMany("Personels")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("personelTrackingSystem.Domain.Entities.TeamEntity", "Team")
                        .WithMany("PersonelEntities")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("personelTrackingSystem.Domain.Entities.ProjectEntity", b =>
                {
                    b.HasOne("personelTrackingSystem.Domain.Entities.PersonelEntity", "Personel")
                        .WithMany("ProjectEntities")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("personelTrackingSystem.Domain.Entities.SalaryEntity", b =>
                {
                    b.HasOne("personelTrackingSystem.Domain.Entities.PersonelEntity", "Personel")
                        .WithMany("SalaryEntities")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("personelTrackingSystem.Domain.Entities.DepartmentEntity", b =>
                {
                    b.Navigation("Personels");
                });

            modelBuilder.Entity("personelTrackingSystem.Domain.Entities.PersonelEntity", b =>
                {
                    b.Navigation("AnnualLeave");

                    b.Navigation("EntryEntities");

                    b.Navigation("LateArrival");

                    b.Navigation("ProjectEntities");

                    b.Navigation("SalaryEntities");
                });

            modelBuilder.Entity("personelTrackingSystem.Domain.Entities.TeamEntity", b =>
                {
                    b.Navigation("PersonelEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
